### DISCUSSION TITLE
Trouble only exposing ESPHome devices while not exposing Tasmota devices.

### DISCUSSION THREAD

**Discussion by st2000** [hass-emulated-hue/core#620] [General]
I would like to only expose ESPHome devices throught Emulated Hue because the Tasmota devices on the network already emulate a Philips Hue interface. Exposing everything HA finds as a Philips Hue device creates duplicate Philips Hue devices for the Tasmota devices which breaks Alexa. I am trying to only expose the ESPHome devices (called "snpanel100)relay_1" and "_2") below. But this version in my configuration.yaml file appears to expose nothing:

```
# Amazon Echo example configuration.yaml entry
emulated_hue:
  listen_port: 80
  expose_by_default: false
#   exposed_domains:
#     - light
  entities:
    switch.nspanel100_relay_1:
      hidden: false
      name: "Porch"
    switch.nspanel100_relay_2:
      hidden: false
      name: 'Garage'    
# Amazon Echo/Alexa stopped working on different ports. Search for "Philips Hue Bridge V1 (round)" in the Alexa App to discover devices.

```
