### DISCUSSION TITLE
Docker Start Commands

### DISCUSSION THREAD

**Discussion by andrel0815** [hass-emulated-hue/core#78] [Q&A] [answered]
Hi,
when will you give us those docker commands to use the addon with a manual installation of home assistant? :) 
My tests to run the image end in this error message:
    raise RuntimeError("Please provide a valid url and token!")
RuntimeError: Please provide a valid url and token!

Best regards and thanks for your awesome work

Andre

**Comment by bitmadao** [comment]
I am also looking forward to those start commands for docker 👍 

In the meantime, I was able to get the image going by passing Environment variables `HASSIO_TOKEN` and `HASS_URL` in my docker-compose.

That gets me far enough that I am able to see a "Home Assistant" bridge with the right IP-address in the Bridge pairing menu for Hue Essentials, but I haven't found a way to "Press the push-link button on the bridge."

Anyway, we all thank you for your development efforts!

```
version: "3.3"
services:
  hassemulatedhue:
    image: marcelveldt/hass-emulated-hue
    container_name: hassemulatedhue
    network_mode: host
    environment:
      HASSIO_TOKEN: "MyLongtermToken"      
      HASS_URL: "https://MyIPAddress:8123/"
    restart: unless-stopped
```

**Comment by alexyao2015** [comment, marked as answer]
Sorry for the delay on this one! Seems like notifications on discussions do not work. 

There is currently a bug with the latest version, requring -t for entertainment to function. In the future, this will be fixed.

```
docker run -t -d --network=host -e HASS_TOKEN=abc -e HASS_URL=123 ghcr.io/hass-emulated-hue/core:0.2.0
```

**Reply by bitmadao** [reply]
This helped me greatly.
Is it to early to share a path for `-v`, for persistent storage?
In any case, this worked great and I was able to use disco lights on my color bulbs. 
Good times were had!

**Reply by alexyao2015** [reply]
Sure! You need to mount `/config/hass-emulated-hue`

**Reply by alexyao2015** [reply]
I realized I provided the incorrect mount location. Use `/root/.emulated_hue/` as the location changes when outside of HASS. You can alternatively change the internal mount location by using `APPDATA`.

**Reply by alexyao2015** [reply]
For those that prefer docker hub, we also publish all our images to there as well. 
https://hub.docker.com/r/hassemulatedhue/core

**Reply by bitmadao** [reply]
Thanks so much for keeping this thread going Alex.
With your mounting instructions I have been able to add persistence to the hub pairing process, using `--mount source=hue-emulated-vol,destination=/config/.emulated_hue -e APPDATA=/config/.emulated_hue`

This has resulted in a usable setup and I thank you for your help!

Remaining wishlist
- get rid of the need for `-t`, or find another workaround for docker-compose, as the docker-compose equivilant `tty: true` does not seem to work as a workaround for the entertainment issue in your first response
- `-v /path/to/my/files:/path/to/config/in/container`, as opposed to `--mount`. This could just be user error on my part, but I haven't been able to get persistence to work with regular folders and I'm not yet completely versed in working with mount volumes.

Having said that, your addon is very nice and I thank you for making it available to us!
Best
Dag

**Reply by alexyao2015** [reply]
-t is no longer required as of 0.2.1. -v should be working. Just make sure to not mix up the source and destination folders.

**Reply by bitmadao** [reply]
Ah, my docker-compose.yml had a malformed HASS_URL, so that's on me!
Yes, I was able to remove -t/tty.
Still having trouble with -v volumes in docker-compose though, 
This is what I have in my docker-compose.yml as of now https://paste.ubuntu.com/p/CdPNX6GnbR/
Persistence works with the --mount syntax for regular docker though.

**Reply by alexyao2015** [reply]
Just read over the code again. Sorry about the confusion. You would want to use `DATA_DIR` not `APPDATA` to change the internal storage location. Furthermore, its not really necessary for docker. Just mount `/root/.emulated_hue` directly and forget about using either.

**Reply by bitmadao** [reply]
Been a few days since last post from me.
I can report that I am happily using hass-emulated-hue in my overall smart-home docker-compose with the following:
```  
  hassemulatedhue:
    image: hassemulatedhue/core
    container_name: hass-emulated-hue
    network_mode: host
    environment:
      HASS_TOKEN: "myLongtermTokenFromHass"    
      HASS_URL: "https://myIpAdress:8123"
      DATA_DIR: "/config/.emulated-hue"
    volumes:
      - ./hass-emulated-hue:/config/.emulated-hue
    restart: unless-stopped
```
I am unable to get persistence to work by not overriding `DATA_DIR` but overriding it works perfectly, so it's not an issue for me.

Thanks for all your efforts.
