### ISSUE TITLE
Color correction and transition time

### ISSUE THREAD

**Issue by Laxilef** [hass-emulated-hue/core#160]
Hello.

Is it possible to add color correction? Not all lamps have the same color with the same (x, y or hue). Z2M supports correction, but only for hue format: 
`zigbee2mqtt/FRIENDLY_NAME/set with payload {"color": {"hue": HUE, "saturation": SATURATION}}`

I tried to forcibly add in the z2m config (devices.yaml) hs in supported_color_modes, but hass-emulated-hue sends x, y to the service. 
```
'0x...':
  friendly_name: livingroom_lamp_left
  optimistic: true
  transition: 0
  hue_correction:
    - in: 240
      out: 150
    - in: 265
      out: 285
    - in: 71
      out: 90
  device_options:
    supported_color_modes: 
      - "xy"
      - "color_temp"
      - "hs"
    color_mode: "hs"
  qos: 0
  debounce: 0
```
 Log:
`2021-06-07 07:33:51,987 DEBUG emulated_hue.api -- {'transitiontime': 8, 'xy': [0.4090004861354828, 0.5180078148841858]}`

And another question. How can I make the transitiontime shorter? Colors change very slooowly :(
On dynamic scenes in movies, it does not look very good. 

Thanks.
