### ISSUE TITLE
Using a light template entity won't fire the turn_on when used from the remote

### ISSUE THREAD

**Issue by kalhimeo** [hass-emulated-hue/core#190]
**Describe the bug**

I created a light template which is used to turn_on, turn_off, and set brightness via the emulated hue integration (triggered from an Harmony Companion remote control).
The light template works as expected when I turn it "on" or "off" from the HA web interface, but when I use the harmony remote button the "turn_on" is not executed (HA detects the turn_on command as the light template entity state goes to "on", but the service it should call from the template is not executed).
All the other commands work (turn_off, set_level) but not the turn_on, it 's very strange.

**Steps to Reproduce**

1. Create a light template, ie.
```
- platform: template
  lights:
    emulated_test_template:
      friendly_name: "Emulated Hue - Test"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.target_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.target_light
```
2. Expose the template to emulated hue
```
emulated_hue:
  expose_by_default : false
  entities:
    emulated_test_template:
      name: "Hue Test"
      hidden: false
```
3. Restart HA, test the light template entity (emulated_test_template) via the developer tools : normally it works as expected
4. Assign the "Hue Test" from emulated_hue to a button, in my case on a Harmony Companion Remote.
5. Test the button on the remote, long press "turn off" effectively turn off the "target light", but short press "turn on" doesn't work although HA will correctly change the state of the light template.

**Expected behavior**

Pressing the button on the remote should effectively turn on the "target light", but only changes the state of the template entity

**Logs**

The problem does not generate any error nor warning in logs

**Hardware Info:**
 - Architecture (Ex: x86, ARM): x86
 - Addon version (Ex: stable or dev): Built-in HA OS 2021.06.8

**Additional context**

None
