### ISSUE TITLE
os.replace in save_json within utils.py throwing exception

### ISSUE THREAD

**Issue by mullermn** [hass-emulated-hue/core#251]
**Describe the bug**

File not found exception raised in function that backs up existing config (emulated_hue.json), even though file does exist and operation appears to be succeeding.

**Steps to Reproduce**

Seems to be driven by any changes in state in bulbs etc. Happens multiple times a minute sometimes but long periods without an exception can pass other times.

**Expected behavior**

emulated_hue.json copied to emulated_hue.json.backup with no exception raised

**Logs**

Error log:
```
emulated_hue         | 2021-12-27 09:34:49,587 ERROR aiohttp.server -- Error handling request
emulated_hue         | Traceback (most recent call last):
emulated_hue         |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
emulated_hue         |     resp = await self._request_handler(request)
emulated_hue         |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
emulated_hue         |     resp = await handler(request)
emulated_hue         |   File "/app/emulated_hue/api.py", line 82, in wrapped_func
emulated_hue         |     if not username or not await cls.config.async_get_user(username):
emulated_hue         |   File "/app/emulated_hue/config.py", line 296, in async_get_user
emulated_hue         |     await self.async_set_storage_value("users", username, user_data)
emulated_hue         |   File "/app/emulated_hue/config.py", line 255, in async_set_storage_value
emulated_hue         |     await async_save_json(self.get_path(CONFIG_FILE), self._config)
emulated_hue         |   File "/app/emulated_hue/utils.py", line 123, in async_save_json
emulated_hue         |     return await loop.run_in_executor(None, save_json, filename, data)
emulated_hue         |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
emulated_hue         |     result = self.fn(*self.args, **self.kwargs)
emulated_hue         |   File "/app/emulated_hue/utils.py", line 130, in save_json
emulated_hue         |     os.replace(filename, safe_copy)
emulated_hue         | FileNotFoundError: [Errno 2] No such file or directory: '/root/.emulated_hue/emulated_hue.json' -> '/root/.emulated_hue/emulated_hue.json.backup'
```

Directory listing showing file IS being updated:
```
root@zz-host:/home/user# ls -la config_emulated_hue/
total 64
drwxr-xr-x  2 root root  4096 Dec 27 09:45 .
drwxr-xr-x 10 ara  ara   4096 Dec 27 08:43 ..
-rw-r--r--  1 root root   227 Dec 22 11:22 .cert_key.pem
-rw-r--r--  1 root root   721 Dec 22 11:22 .cert.pem
-rw-r--r--  1 root root 14874 Dec 27 09:45 emulated_hue.json
-rw-r--r--  1 root root 14874 Dec 27 09:45 emulated_hue.json.backup
```

Compose script:
```
version: '3'
services:
  hass-emulated-hue:
    container_name: emulated_hue
    network_mode: host
    restart: unless-stopped
    environment:
      - HASS_TOKEN=mytoken
      - HASS_URL=http://myurl
      - VERBOSE=true #false
    image: ghcr.io/hass-emulated-hue/core:0.2.10 # <<< Desired release version here
    volumes:
      - /home/user/config_emulated_hue:/root/.emulated_hue/
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
ARM
 - Addon version (Ex: stable or dev): 
0.2.10 and 0.2.9 (note - not running as an addon)
 - OS (Ex: Windows 10, Ubuntu Buster): 
Docker on Raspbian 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 
Raspberry pi 2B with SD card storage

**Additional context**
